#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="elasticSolidFoam"  
##slidingFrictionFoam

#runApplication blockMesh
./copymesh.sh 
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap
runApplication $application
